FIX: echo -e support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # MIT License
 
 # Copyright (c) 2020 DarkElvenAngel
@@ -21,9 +22,15 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-[ -f makefile.conf ] && { printf "\033[31mERROR\033[0;1m:  makefile.conf already exists. run make mrproper first!\033[0m\n"; exit 1;}
+# determine if we should use '-e' for echo command
+TEST_FOR_E=`echo -e 'E'`
+[ "$TEST_FOR_E" = '-e E' ] && ECHO="echo" || ECHO="echo -e"
+
+[ -f makefile.conf ] && { $ECHO "\033[31mERROR\033[0;1m: makefile.conf already exists. run make mrproper first!\033[0m"; exit 1;}
+
 [ -d build ] || mkdir build
-printf "\033[37;1mARGON ONE DAEMON CONFIGURING ...\033[0m\n"
+$ECHO  "\033[37;1mARGON ONE DAEMON CONFIGURING ...\033[0m"
+
 if [ "x$TARGET_DISTRO" != "x" ]
 then
     DISTRO=$TARGET_DISTRO
@@ -37,10 +44,10 @@ PACKAGESYS=0
 INITSYS="SYSTEMD"
 [ "x$BOOTLOC" != "x" ] && BOOTLOC="/boot"
 
-printf "\033[1mDistro check [$DISTRO] : \033[0m"
+$ECHO -n "\033[1mDistro check [$DISTRO] : \033[0m"
 if [ -d "OS/$DISTRO" ]
 then 
-    [ -f "OS/$DISTRO/OS.conf" ] && . OS/$DISTRO/OS.conf
+    [ -f "OS/$DISTRO/OS.conf" ] && source OS/$DISTRO/OS.conf
     case $STATUS in
     "OK")
         COLOUR=32
@@ -52,42 +59,42 @@ then
         COLOUR=31
         ;;
     esac
-    printf "\033[${COLOUR};1m${STATUS}\033[0m\n" 
+    $ECHO "\033[${COLOUR};1m${STATUS}\033[0m" 
 else
-    printf "\033[33;1mWARNING: UNKNOWN DISTRO, The installer may not work\033[0m\n"
+    $ECHO "\033[33;1mWARNING: UNKNOWN DISTRO, The installer may not work\033[0m"
 fi
 
-printf "\033[1mSYSTEM CHECK\033[0m\n"
-echo -n "gcc : "
+$ECHO "\033[1mSYSTEM CHECK\033[0m"
+$ECHO -n "gcc : "
 command -v gcc >/dev/null 2>&1 && GCC=1 || GCC=0
-[ $GCC = 1 ] && printf "\033[32mOK\033[0m\n" || printf "\033[31mERR\033[0m\n"
-echo -n "dtc : "
+[ $GCC = 1 ] && $ECHO "\033[32mOK\033[0m" || $ECHO "\033[31mERR\033[0m"
+$ECHO -n "dtc : "
 command -v dtc > /dev/null 2>&1 && DTC=1 || DTC=0
-[ $DTC = 1 ] && printf "\033[32mOK\033[0m\n" || printf "\033[31mERR\033[0m\n"
-echo -n "make : "
+[ $DTC = 1 ] && $ECHO "\033[32mOK\033[0m" || $ECHO "\033[31mERR\033[0m"
+$ECHO -n "make : "
 command -v make >/dev/null 2>&1 && MAKE=1 || MAKE=0
-[ $MAKE = 1 ] && printf "\033[32mOK\033[0m\n" || printf "\033[31mERR\033[0m\n"
+[ $MAKE = 1 ] && $ECHO "\033[32mOK\033[0m" || $ECHO "\033[31mERR\033[0m"
 
 if [ $PACKAGESYS = 1 ]
 then
     I2CBUS=1
 else
-    echo -n "I2C Bus check : "
-    [ -c /dev/i2c-1 ] && { I2CBUS=1 ; printf  "\033[32mENABLED\033[0m\n";} || { I2CBUS=0 ; printf  "\033[1mNOT ENABLED\033[0m\n";}
-    printf  "\033[1;37mCHECKING OPTIONAL SYSTEMS\033[0m\n"
-    echo -n "bash-autocomplete : "
-    [ -d /etc/bash_completion.d ] && { AUTOC=1 ; printf "\033[32mOK\033[0m\n";} || { AUTOC=0 ; printf "\033[1mNOT INSTALLED\033[0m\n";}
-    echo -n "logrotate : "
+    $ECHO -n "I2C Bus check : "
+    [ -c /dev/i2c-1 ] && { I2CBUS=1 ; $ECHO  "\033[32mENABLED\033[0m";} || { I2CBUS=0 ; $ECHO  "\033[1mNOT ENABLED\033[0m";}
+    $ECHO  "\033[1;37mCHECKING OPTIONAL SYSTEMS\033[0m"
+    $ECHO -n "bash-autocomplete : "
+    [ -d /etc/bash_completion.d ] && { AUTOC=1 ; $ECHO "\033[32mOK\033[0m";} || { AUTOC=0 ; $ECHO "\033[1mNOT INSTALLED\033[0m";}
+    $ECHO -n "logrotate : "
     command -v logrotate  >/dev/null 2>&1 && LOGROTATE=1 || LOGROTATE=0
-    [ $LOGROTATE = 1 ] && printf "\033[32mINSTALLED\033[0m\n" || printf "\033[1mNOT INSTALLED\033[0m\n"
+    [ $LOGROTATE = 1 ] && $ECHO "\033[32mINSTALLED\033[0m" || $ECHO "\033[1mNOT INSTALLED\033[0m"
 fi
 
-printf "\033[1mDependency Check :\033[0m"
+$ECHO -n "\033[1mDependency Check : \033[0m"
 if [ `expr $GCC + $DTC + $MAKE` = 3 ]
 then
-    printf  "\033[32m Successful\033[0m\n"
+    $ECHO  "\033[32mSuccessful\033[0m"
 else
-    printf  "\033[31m Failed! Please install the missing tool(s)\033[0m\n"
+    $ECHO  "\033[1;31mFailed! Please install the missing tool(s)\033[0m"
     exit 1
 fi
 
@@ -107,17 +114,18 @@ else
 fi
 if [ "x$DISABLE_POWERBUTTON" != "x" ]
 then
-    printf "Power Button is \033[1mDISABLED\033[0m\n"
+    $ECHO "Power Button is \033[1mDISABLED\033[0m"
     echo "DISABLE_POWER_BUTTON_SUPPORT=1" >> makefile.conf
 fi
 if [ "x$USE_SYSFS_TEMP" != "x" ]
 then
-    printf "Daemon will use \033[1m${USE_SYSFS_TEMP}\033[0m for temperature sensor\n"
+
+    $ECHO "Daemon will use \033[1m${USE_SYSFS_TEMP}\033[0m for temperature sensor"
     echo "USE_SYSFS_TEMP=${USE_SYSFS_TEMP}" >> makefile.conf
 fi
 if [ "x$RUN_IN_FOREGROUND" != "x" ]
 then
-    printf "Daemon will use run only in foreground and not fork\n"
+    $ECHO "Daemon will use run only in foreground and not fork"
     echo "RUN_IN_FOREGROUND=1" >> makefile.conf
 fi
 exit 0
